services:
  server:
    build:
      context: "./"
      dockerfile: "./server/Dockerfile"
    image: "server:v1"
    container_name: "server"
    ports: 
      - "8080:8080"
    networks:
        - internet
    volumes:
        - ./database:/app/database:rw
  
  client:
    depends_on: 
      - server
    build:
      context: "./"
      dockerfile: "./client/Dockerfile"
    image: "client:v1"
    tty: true
    stdin_open: true
    networks:
        - internet

networks:
  internet:
    driver: bridge
    name: "internet"

